services:
  nginx:
    image: nginx:1.27-alpine
    container_name: air_pollution_app_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend-next/out:/usr/share/nginx/html:ro
    depends_on:
      - backend

  backend:
    image: ghcr.io/miranas/air_pollution_app:latest
    container_name: air_pollution_app
    restart: always
    expose:
      - "5000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
  
  redis:
    image: redis:7.2-alpine
    container_name: air_pollution_app__redis
    restart: always
    expose:
      - "6379"
      

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: air_pollution_app_prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=7d'
    volumes:
      # bind mount, file mapping
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.4.2
    container_name: air_pollution_app_grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  postgres:
    image: pgvector/pgvector:pg17
    container_name: airquality_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:2.21.5
    container_name: air_pollution_app_portainer
    restart: always
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data


  ollama:
    image: ollama/ollama:latest
    container_name: airquality_ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "127.0.0.1:11434:11434"
    restart: unless-stopped
    networks:
      - default

    
# create volumes
volumes:
  prometheus_data:
  grafana_data:
  portainer_data:
  ollama_data:
  postgres_data:






    


    



